### ISSUE TITLE
Error being thrown during server startup

### ISSUE THREAD

**Issue by KevBelisle** [emilianomaccaferri/query#9]
I'm getting errors while the server is starting, and despite wrapping the call to `.fullStat()` in a `try/catch` block, I am not catching the exception.

```javascript
\node_modules\minecraft-query\Query.js:31
                var players = final[1].split("\0").filter((item) => {
                                       ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Socket.<anonymous> (C:\Users\Kevin\Development\minecraft-discord-bot\node_modules\minecraft-query\Query.js:31:40)
    at Socket.emit (node:events:390:28)
    at UDP.onMessage [as onmessage] (node:dgram:939:8)
```

**Comment by emilianomaccaferri** [comment]
can you provide some code?

**Comment by KevBelisle** [comment]
I edited the Query.js file locally, and added these extra logs (starting at line 28):

```javascript
            if (this.full_stat) {

                console.log("---------");
                console.log(data.toString('utf-8', 11));
                console.log("---------");

                var final = data.toString('utf-8', 11).split("\x00\x01player_\x00\x00"); // splicing the output as suggested
                var kv = final[0].split("\0");

                var players = [];
                try {
                    players = final[1].split("\0").filter((item) => {
                        return item != "";
                    });
                } catch {
                    console.log("Caught the exception!")
                }
```

And got this in my logs:
```
---------
9
---------
Caught the exception!
```



This is on a Forge 1.16.5 server running a pretty heavy modpack (Medieval Minecraft), so startup takes a few minutes.

**Comment by KevBelisle** [comment]
My main issue is that I am unable to catch to exception in my code that calls `.fullStat()`

And I think it is because of this: https://stackoverflow.com/a/47163758

**Comment by emilianomaccaferri** [comment]
it's strange because the query shouldn't be available until the server has started up.
if i try to query the server while it's starting the query simply fails with `rror: Challenge token generation timeout`.

i really don't know about modded minecraft servers (the package was tested on spigot/vanilla servers) and i don't know the modpack either so really can't help on that side

well, i pushed some changes that should fix the issue, since i don't have any way to reproduce the bug because i don't have the modpack (i basically wrapped the whole basicStat() in a try/catch, as it should have been and idk why it wasn't).
just run `npm install minecraft-query@latest` and let me know if something changes!
